# Generated by Django 4.2 on 2026-03-04 14:07

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.TextField(verbose_name='Sent To')),
                ('subj', models.TextField(verbose_name='Subject')),
                ('text', models.TextField(verbose_name='Text')),
                ('sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Emails To Send',
            },
        ),
        migrations.CreateModel(
            name='Insert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_checked', models.DateField(default=datetime.date.today, verbose_name='Date Checked')),
                ('location', models.TextField(verbose_name='Manufacturers instructions link')),
                ('initial_action', models.CharField(max_length=150, verbose_name='Initial Action Taken')),
                ('final_action', models.CharField(blank=True, max_length=150, null=True, verbose_name='Final Action Taken')),
                ('version', models.CharField(max_length=15, verbose_name='Kit Insert Version')),
                ('date_confirmed', models.DateField(blank=True, null=True, verbose_name='Date Confrimed')),
                ('checked_user', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='1+', to=settings.AUTH_USER_MODEL)),
                ('confirmed_user', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='2+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kit Inserts',
            },
        ),
        migrations.CreateModel(
            name='Internal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=4, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Stock Numbers',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_no', models.CharField(max_length=50, verbose_name='Lot Number')),
                ('po', models.CharField(max_length=20, verbose_name='Purchase Order')),
                ('date_rec', models.DateField(default=datetime.date.today, verbose_name='Date Received')),
                ('cond_rec', models.CharField(choices=[('GD', 'Good'), ('NA', 'N/A, Made in House'), ('DU', 'Damaged - Usable'), ('UN', 'Damaged - Not Usable')], default='GD', max_length=2, verbose_name='Condition Received')),
                ('date_exp', models.DateField(verbose_name='Expiry Date')),
                ('date_op', models.DateField(blank=True, null=True)),
                ('is_op', models.BooleanField(default=False)),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date Finished')),
                ('finished', models.BooleanField(default=False)),
                ('fin_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Finished Reason')),
                ('vol_rec', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Volume Received (µl)')),
                ('current_vol', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Current Volume (µl)')),
                ('accept_reason', models.CharField(blank=True, max_length=150, null=True, verbose_name='Acceptance Reason')),
                ('fin_user', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='3+', to=settings.AUTH_USER_MODEL, verbose_name='Finished By')),
                ('internal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock_web.internal', verbose_name='Stock Number')),
            ],
            options={
                'verbose_name_plural': 'Inventory Items',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reagents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cat_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Catalogue Number')),
                ('count_no', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unopened Items')),
                ('open_no', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Opened Items')),
                ('min_count', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Stock Level')),
                ('track_vol', models.BooleanField(default=False, verbose_name='Volume Tracked')),
                ('inserts_req', models.BooleanField(default=True, verbose_name='Will this item come with Manufacturer’s Instructions?')),
                ('is_active', models.BooleanField(default=True)),
                ('kit_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kit Name')),
                ('unit_of_measurement', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unit of Measurement')),
                ('standing_order', models.BooleanField(default=False, verbose_name='Standing Order')),
                ('latest_insert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock_web.insert', verbose_name='Most Recent Kit Insert')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock_web.location')),
            ],
            options={
                'verbose_name_plural': 'Reagents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('shelf_life', models.PositiveIntegerField(verbose_name='Shelf Life (Months)')),
                ('track_vol', models.BooleanField(default=False, verbose_name='Volume Tracked')),
                ('witness_req', models.BooleanField(default=False, verbose_name='Witness Required?')),
                ('added_by', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('comp1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component1', to='stock_web.reagents', verbose_name='component 1')),
                ('comp10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component10', to='stock_web.reagents', verbose_name='component 10')),
                ('comp2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component2', to='stock_web.reagents', verbose_name='component 2')),
                ('comp3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component3', to='stock_web.reagents', verbose_name='component 3')),
                ('comp4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component4', to='stock_web.reagents', verbose_name='component 4')),
                ('comp5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component5', to='stock_web.reagents', verbose_name='component 5')),
                ('comp6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component6', to='stock_web.reagents', verbose_name='component 6')),
                ('comp7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component7', to='stock_web.reagents', verbose_name='component 7')),
                ('comp8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component8', to='stock_web.reagents', verbose_name='component 8')),
                ('comp9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component9', to='stock_web.reagents', verbose_name='component 9')),
                ('reagent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Reagent_ID', to='stock_web.reagents', verbose_name='Reagent ID')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('comp1', models.ForeignKey(blank=True, limit_choices_to={'finished': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comp1', to='stock_web.inventory')),
                ('comp10', models.ForeignKey(blank=True, limit_choices_to={'finished': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comp10', to='stock_web.inventory')),
                ('comp2', models.ForeignKey(blank=True, limit_choices_to={'finished': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comp2', to='stock_web.inventory')),
                ('comp3', models.ForeignKey(blank=True, limit_choices_to={'finished': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comp3', to='stock_web.inventory')),
                ('comp4', models.ForeignKey(blank=True, limit_choices_to={'finished': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comp4', to='stock_web.inventory')),
                ('comp5', models.ForeignKey(blank=True, limit_choices_to={'finished': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comp5', to='stock_web.inventory')),
                ('comp6', models.ForeignKey(blank=True, limit_choices_to={'finished': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comp6', to='stock_web.inventory')),
                ('comp7', models.ForeignKey(blank=True, limit_choices_to={'finished': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comp7', to='stock_web.inventory')),
                ('comp8', models.ForeignKey(blank=True, limit_choices_to={'finished': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comp8', to='stock_web.inventory')),
                ('comp9', models.ForeignKey(blank=True, limit_choices_to={'finished': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comp9', to='stock_web.inventory')),
                ('creator_user', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock_web.recipe', verbose_name='Recipe Name')),
            ],
            options={
                'verbose_name_plural': 'Solutions',
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VolUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DecimalField(decimal_places=2, max_digits=7)),
                ('end', models.DecimalField(decimal_places=2, max_digits=7)),
                ('used', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date', models.DateField(default=datetime.date.today)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock_web.inventory')),
                ('sol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock_web.solutions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Volume Usage',
            },
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val_date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('val_run', models.CharField(max_length=25, verbose_name='Run Name')),
                ('val_user', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='reagents',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock_web.recipe'),
        ),
        migrations.AddField(
            model_name='reagents',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock_web.room'),
        ),
        migrations.AddField(
            model_name='reagents',
            name='supplier_def',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock_web.suppliers', verbose_name='Default Supplier'),
        ),
        migrations.AddField(
            model_name='reagents',
            name='team_def',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock_web.teams', verbose_name='Default Team'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='last_usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock_web.volusage'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock_web.location'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='op_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='2+', to=settings.AUTH_USER_MODEL, verbose_name='Opened by'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='reagent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock_web.reagents'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='rec_user',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='1+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventory',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock_web.room'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='sol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock_web.solutions'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock_web.suppliers'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock_web.teams'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='val',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock_web.validation', verbose_name='Validation Run'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='witness',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='4+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insert',
            name='reagent',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='stock_web.reagents'),
        ),
        migrations.CreateModel(
            name='EmailGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock_web.teams')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_made', models.DateField(default=datetime.date.today, verbose_name='Date Made')),
                ('comment', models.TextField(max_length=250, verbose_name='comment')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock_web.inventory')),
                ('user', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Item Comments',
            },
        ),
    ]
