# Generated by Django 4.2 on 2025-03-31 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_web', '0002_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='stock_web.room'),
            preserve_default=False,
        ),
    ]
