# Generated by Django 4.2 on 2025-04-01 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_web', '0004_location_reagents_kit_name_alter_inventory_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagents',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock_web.location'),
        ),
        migrations.AddField(
            model_name='reagents',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock_web.room'),
        ),
    ]
