# Generated by Django 4.2 on 2025-04-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_web', '0005_reagents_location_reagents_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reagents',
            name='location',
        ),
        migrations.RemoveField(
            model_name='reagents',
            name='room',
        ),
    ]
