# Generated by Django 4.2 on 2025-04-01 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_web', '0007_staff'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staff',
            table='STAFF',
        ),
    ]
