# Generated by Django 4.2 on 2025-04-01 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_web', '0008_alter_staff_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='STAFF',
        ),
        migrations.AddField(
            model_name='reagents',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock_web.location'),
        ),
        migrations.AddField(
            model_name='reagents',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock_web.room'),
        ),
    ]
