# Generated by Django 4.2 on 2025-04-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_web', '0009_delete_staff_reagents_location_reagents_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='STAFF',
            fields=[
                ('STAFF_CODE', models.CharField(db_column='STAFF_CODE', max_length=4, primary_key=True, serialize=False)),
                ('PASSWORD', models.CharField(max_length=10)),
                ('NAME', models.CharField(max_length=50)),
                ('EMAIL', models.EmailField(max_length=70, verbose_name='email')),
                ('EMPLOYMENT_END_DATE', models.DateTimeField()),
            ],
            options={
                'db_table': '[dbo].[STAFF]',
                'managed': False,
            },
        ),
    ]
