# Generated by Django 4.2 on 2025-09-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_web', '0010_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='STAFF',
        ),
        migrations.AlterField(
            model_name='insert',
            name='location',
            field=models.TextField(verbose_name='Manufacturers instructions link'),
        ),
    ]
