# Generated by Django 4.2 on 2025-09-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_web', '0011_delete_staff_alter_insert_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagents',
            name='unit_of_measurement',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Unit of Measurement'),
        ),
    ]
