# Generated by Django 4.2 on 2025-09-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_web', '0012_reagents_unit_of_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagents',
            name='standing_order',
            field=models.BooleanField(default=False, verbose_name='Standing Order'),
        ),
    ]
