# Generated by Django 4.2 on 2025-10-09 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_web', '0013_reagents_standing_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForceReset',
        ),
    ]
